"""add cancelled_by_patient to appointments

Revision ID: 04c41d38699e
Revises: 51774d3b9564
Create Date: 2026-04-27 08:39:29.237701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c41d38699e'
down_revision: Union[str, Sequence[str], None] = '51774d3b9564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cancelled_by_patient', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'cancelled_by_patient')
    # ### end Alembic commands ###
