"""replace full_name with first_name last_name, add cnp and gender

Revision ID: 6344b7f93298
Revises: 7ba88f1c54b9
Create Date: 2026-04-22 13:23:25.146613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6344b7f93298'
down_revision: Union[str, Sequence[str], None] = '7ba88f1c54b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('cnp', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('gender', sa.String(), nullable=True))
    op.drop_column('patients', 'cnp_encrypted')
    op.drop_column('patients', 'date_of_birth_encrypted')
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('patients', sa.Column('date_of_birth_encrypted', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('cnp_encrypted', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'cnp')
    # ### end Alembic commands ###
