"""add reason to appointments, diagnosis to medical_records

Revision ID: 90bb36d45bb1
Revises: 6344b7f93298
Create Date: 2026-04-22 14:20:56.719622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90bb36d45bb1'
down_revision: Union[str, Sequence[str], None] = '6344b7f93298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reason', sa.String(length=500), nullable=True))
    op.add_column('medical_records', sa.Column('diagnosis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'diagnosis')
    op.drop_column('appointments', 'reason')
    # ### end Alembic commands ###
