"""add treatment to medical_records

Revision ID: c51af847677b
Revises: 90bb36d45bb1
Create Date: 2026-04-22 15:00:23.590566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51af847677b'
down_revision: Union[str, Sequence[str], None] = '90bb36d45bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('treatment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'treatment')
    # ### end Alembic commands ###
